// <auto-generated />
using System;
using GestionProjects.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionProjects.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251230043118_AddCapaciteRessourcesAndBudgetJustification")]
    partial class AddCapaciteRessourcesAndBudgetJustification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionProjects.Domain.Models.AnomalieProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssigneeA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaireResolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreationAnomalie")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Environnement")
                        .HasColumnType("int");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleConcerne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priorite")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RapporteePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.ToTable("AnomaliesProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdresseIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnciennesValeurs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntiteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NouvellesValeurs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.ChargeProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ChargePrevisionnelle")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ChargeReelle")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSaisieChargeReelle")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjetId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SaisieParId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SemaineDebut")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId1");

                    b.HasIndex("RessourceId");

                    b.HasIndex("SaisieParId");

                    b.HasIndex("ProjetId", "SemaineDebut", "RessourceId")
                        .IsUnique();

                    b.ToTable("ChargesProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.CharteProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprouvePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssuranceQualite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ChefProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraintesInitiales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRevision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSignatureChefProjet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSignatureSponsor")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DemandeurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailChefProjet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomProjet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroProjet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroRevision")
                        .HasColumnType("int");

                    b.Property<string>("ObjectifProjet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perimetre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RedigePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RisquesInitiaux")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SignatureChefProjet")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SignatureChefProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SignatureSponsor")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SignatureSponsorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sponsors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChefProjetId");

                    b.HasIndex("DemandeurId");

                    b.HasIndex("ProjetId")
                        .IsUnique();

                    b.HasIndex("SignatureChefProjetId");

                    b.HasIndex("SignatureSponsorId");

                    b.ToTable("CharteProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DelegationChefProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DelegantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DelegueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DelegantId");

                    b.HasIndex("DelegueId");

                    b.HasIndex("ProjetId");

                    b.ToTable("DelegationsChefProjet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DelegationValidationDSI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DSIId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DelegueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DSIId");

                    b.HasIndex("DelegueId");

                    b.ToTable("DelegationsValidationDSI");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DemandeClotureProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentaireDSI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaireDemandeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaireDirecteurMetier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateClotureFinale")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSouhaiteeCloture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidationDSI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidationDemandeur")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidationDirecteurMetier")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DemandeParId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<bool>("EstTerminee")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatutValidationDSI")
                        .HasColumnType("int");

                    b.Property<int>("StatutValidationDemandeur")
                        .HasColumnType("int");

                    b.Property<int>("StatutValidationDirecteurMetier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DemandeParId");

                    b.HasIndex("ProjetId");

                    b.ToTable("DemandesClotureProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DemandeProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvantagesAttendus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CahierChargesPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaireDSI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaireDirecteurMetier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contexte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Criticite")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMiseEnOeuvreSouhaitee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidationDM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidationDSI")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DemandeurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DirecteurMetierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DirectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectifs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perimetre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatutDemande")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urgence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DemandeurId");

                    b.HasIndex("DirecteurMetierId");

                    b.HasIndex("DirectionId");

                    b.ToTable("DemandesProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Direction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DSIId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DSIId");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DocumentJointDemande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheminRelatif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DemandeProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeposeParId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeProjetId");

                    b.HasIndex("DeposeParId");

                    b.ToTable("DocumentsJointsDemandes");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.FicheProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BeneficesAttendus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BudgetConsomme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BudgetPrevisionnel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CRReunionsPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("CahierTestsPVRecettePVMEPPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("CharteProjetPresente")
                        .HasColumnType("bit");

                    b.Property<string>("ContexteProblemeAdresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriticiteUrgence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDerniereMiseAJour")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateJustificationEcart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionsAttendues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DemandesArbitrage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DerniereMiseAJourParId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionSynthetique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EcartsBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EquipeProjet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("JustificationEcartBudget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("JustificationParId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectifPrincipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartiesPrenantesCles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerimetreExclu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerimetreInclus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointsForts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointsVigilance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProchainJalon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RapportLeconsApprisesPVCloturePresent")
                        .HasColumnType("bit");

                    b.Property<string>("ResultatsAttendus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntheseRisques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreCourt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreLong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeProjet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WBSPlanningRACIBudgetPresent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DerniereMiseAJourParId");

                    b.HasIndex("JustificationParId");

                    b.HasIndex("ProjetId")
                        .IsUnique();

                    b.ToTable("FicheProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.HistoriqueChefProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChefProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChefProjetId");

                    b.HasIndex("ProjetId");

                    b.ToTable("HistoriqueChefProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.HistoriquePhaseProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifieParId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatutProjet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifieParId");

                    b.HasIndex("ProjetId");

                    b.ToTable("HistoriquePhasesProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.JalonCharte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharteProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriteresApprobation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePrevisionnelle")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharteProjetId");

                    b.ToTable("JalonsCharte");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.LivrableProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheminRelatif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeposeParId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeLivrable")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeposeParId");

                    b.HasIndex("ProjetId");

                    b.ToTable("LivrablesProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.MembreProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectionLibelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Fonction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleDansProjet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.ToTable("MembresProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonneesSupplementaires")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntiteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstLue")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeNotification")
                        .HasColumnType("int");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId", "EstLue", "EstSupprime");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.ParametreSysteme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParametresSysteme");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.PartiePrenanteCharte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharteProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharteProjetId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("PartiesPrenantesCharte");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.PortefeuilleProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvantagesAttendus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectifStrategiqueGlobal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RisquesEtMitigations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortefeuillesProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Projet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BilanCloture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CharteValidee")
                        .HasColumnType("bit");

                    b.Property<bool>("CharteValideeParDM")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CharteValideeParDMId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CharteValideeParDSI")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CharteValideeParDSIId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChefProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeProjet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaireRefusCharteDM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaireRefusCharteDSI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaireTechnique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCharteValidee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCharteValideeParDM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCharteValideeParDSI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDernierCalculRAG")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDernierCommentaireTechnique")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinReelle")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMep")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePlanningValideParDM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePlanningValideParDSI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRecetteValidee")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DemandeProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DernierCommentaireTechniqueParId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DirectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("EtatProjet")
                        .HasColumnType("int");

                    b.Property<int>("IndicateurRAG")
                        .HasColumnType("int");

                    b.Property<string>("LeconsApprises")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MepEffectuee")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhaseActuelle")
                        .HasColumnType("int");

                    b.Property<bool>("PlanningValideParDM")
                        .HasColumnType("bit");

                    b.Property<bool>("PlanningValideParDSI")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PortefeuilleProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PourcentageAvancement")
                        .HasColumnType("int");

                    b.Property<bool>("RecetteValidee")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RecetteValideeParId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatutProjet")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharteValideeParDMId");

                    b.HasIndex("CharteValideeParDSIId");

                    b.HasIndex("ChefProjetId");

                    b.HasIndex("DemandeProjetId")
                        .IsUnique();

                    b.HasIndex("DernierCommentaireTechniqueParId");

                    b.HasIndex("DirectionId");

                    b.HasIndex("PortefeuilleProjetId");

                    b.HasIndex("RecetteValideeParId");

                    b.HasIndex("SponsorId");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.RisqueProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreationRisque")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanMitigation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Probabilite")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.ToTable("RisquesProjets");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DirectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CapaciteHebdomadaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDerniereConnexion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DirectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreConnexion")
                        .HasColumnType("int");

                    b.Property<bool>("PeutCreerDemandeProjet")
                        .HasColumnType("bit");

                    b.Property<string>("Prenoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.UtilisateurRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId", "Role")
                        .IsUnique();

                    b.ToTable("UtilisateurRoles");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.AnomalieProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithMany("Anomalies")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.AuditLog", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.ChargeProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Projet", null)
                        .WithMany("Charges")
                        .HasForeignKey("ProjetId1");

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Ressource")
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "SaisiePar")
                        .WithMany()
                        .HasForeignKey("SaisieParId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Projet");

                    b.Navigation("Ressource");

                    b.Navigation("SaisiePar");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.CharteProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "ChefProjet")
                        .WithMany()
                        .HasForeignKey("ChefProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Demandeur")
                        .WithMany()
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithOne("CharteProjet")
                        .HasForeignKey("GestionProjects.Domain.Models.CharteProjet", "ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "SignatureChefProjetUtilisateur")
                        .WithMany()
                        .HasForeignKey("SignatureChefProjetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "SignatureSponsorUtilisateur")
                        .WithMany()
                        .HasForeignKey("SignatureSponsorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChefProjet");

                    b.Navigation("Demandeur");

                    b.Navigation("Projet");

                    b.Navigation("SignatureChefProjetUtilisateur");

                    b.Navigation("SignatureSponsorUtilisateur");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DelegationChefProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Delegant")
                        .WithMany()
                        .HasForeignKey("DelegantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Delegue")
                        .WithMany()
                        .HasForeignKey("DelegueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delegant");

                    b.Navigation("Delegue");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DelegationValidationDSI", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "DSI")
                        .WithMany()
                        .HasForeignKey("DSIId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Delegue")
                        .WithMany()
                        .HasForeignKey("DelegueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DSI");

                    b.Navigation("Delegue");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DemandeClotureProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "DemandePar")
                        .WithMany()
                        .HasForeignKey("DemandeParId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithMany("DemandesCloture")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandePar");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DemandeProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Demandeur")
                        .WithMany()
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "DirecteurMetier")
                        .WithMany()
                        .HasForeignKey("DirecteurMetierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Demandeur");

                    b.Navigation("DirecteurMetier");

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Direction", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "DSI")
                        .WithMany()
                        .HasForeignKey("DSIId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DSI");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DocumentJointDemande", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.DemandeProjet", "DemandeProjet")
                        .WithMany("Annexes")
                        .HasForeignKey("DemandeProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "DeposePar")
                        .WithMany()
                        .HasForeignKey("DeposeParId");

                    b.Navigation("DemandeProjet");

                    b.Navigation("DeposePar");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.FicheProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "DerniereMiseAJourPar")
                        .WithMany()
                        .HasForeignKey("DerniereMiseAJourParId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "JustificationPar")
                        .WithMany()
                        .HasForeignKey("JustificationParId");

                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithOne("FicheProjet")
                        .HasForeignKey("GestionProjects.Domain.Models.FicheProjet", "ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerniereMiseAJourPar");

                    b.Navigation("JustificationPar");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.HistoriqueChefProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "ChefProjet")
                        .WithMany()
                        .HasForeignKey("ChefProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChefProjet");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.HistoriquePhaseProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "ModifieParUtilisateur")
                        .WithMany()
                        .HasForeignKey("ModifieParId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithMany("HistoriquePhases")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModifieParUtilisateur");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.JalonCharte", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.CharteProjet", "CharteProjet")
                        .WithMany("Jalons")
                        .HasForeignKey("CharteProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharteProjet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.LivrableProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "DeposePar")
                        .WithMany()
                        .HasForeignKey("DeposeParId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithMany("Livrables")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeposePar");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.MembreProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithMany("Membres")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Notification", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.PartiePrenanteCharte", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.CharteProjet", "CharteProjet")
                        .WithMany("PartiesPrenantes")
                        .HasForeignKey("CharteProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CharteProjet");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Projet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "CharteValideeParDMUtilisateur")
                        .WithMany()
                        .HasForeignKey("CharteValideeParDMId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "CharteValideeParDSIUtilisateur")
                        .WithMany()
                        .HasForeignKey("CharteValideeParDSIId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "ChefProjet")
                        .WithMany()
                        .HasForeignKey("ChefProjetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionProjects.Domain.Models.DemandeProjet", "DemandeProjet")
                        .WithOne("Projet")
                        .HasForeignKey("GestionProjects.Domain.Models.Projet", "DemandeProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "DernierCommentaireTechniquePar")
                        .WithMany()
                        .HasForeignKey("DernierCommentaireTechniqueParId");

                    b.HasOne("GestionProjects.Domain.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionProjects.Domain.Models.PortefeuilleProjet", "PortefeuilleProjet")
                        .WithMany()
                        .HasForeignKey("PortefeuilleProjetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "RecetteValideePar")
                        .WithMany()
                        .HasForeignKey("RecetteValideeParId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharteValideeParDMUtilisateur");

                    b.Navigation("CharteValideeParDSIUtilisateur");

                    b.Navigation("ChefProjet");

                    b.Navigation("DemandeProjet");

                    b.Navigation("DernierCommentaireTechniquePar");

                    b.Navigation("Direction");

                    b.Navigation("PortefeuilleProjet");

                    b.Navigation("RecetteValideePar");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.RisqueProjet", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Projet", "Projet")
                        .WithMany("Risques")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Service", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Direction", "Direction")
                        .WithMany("Services")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Utilisateur", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.UtilisateurRole", b =>
                {
                    b.HasOne("GestionProjects.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany("UtilisateurRoles")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.CharteProjet", b =>
                {
                    b.Navigation("Jalons");

                    b.Navigation("PartiesPrenantes");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.DemandeProjet", b =>
                {
                    b.Navigation("Annexes");

                    b.Navigation("Projet")
                        .IsRequired();
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Direction", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Projet", b =>
                {
                    b.Navigation("Anomalies");

                    b.Navigation("Charges");

                    b.Navigation("CharteProjet");

                    b.Navigation("DemandesCloture");

                    b.Navigation("FicheProjet");

                    b.Navigation("HistoriquePhases");

                    b.Navigation("Livrables");

                    b.Navigation("Membres");

                    b.Navigation("Risques");
                });

            modelBuilder.Entity("GestionProjects.Domain.Models.Utilisateur", b =>
                {
                    b.Navigation("UtilisateurRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
